//
// Created by betzalel on 18/10/22.
//

#ifndef CPP_DESIGN_PATTERNS_REMAINING_DRIVING_DISTANCE_ALGORITHM_FWD_H
#define CPP_DESIGN_PATTERNS_REMAINING_DRIVING_DISTANCE_ALGORITHM_FWD_H

class RDDA;

#endif //CPP_DESIGN_PATTERNS_REMAINING_DRIVING_DISTANCE_ALGORITHM_FWD_H
