//
// Created by oneshepherdssheep on 09/09/22.
//

#ifndef CPP_DESIGN_PATTERNS_BATTLE_TURN_STATE_FWD_H
#define CPP_DESIGN_PATTERNS_BATTLE_TURN_STATE_FWD_H

class BattleTurnState;

#endif //CPP_DESIGN_PATTERNS_BATTLE_TURN_STATE_FWD_H
