name: linux
on:
  push:
    branches:
      - main
    pull_request:
      - main

env:
  BUILD_TYPE: Debug,Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure
      - run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build

      - name: build
      - run: cmake --build ${{github.workspace}}/build

