name: PVS-Studio build analysis
on: workflow_dispatch
jobs:
  build_and_analyze_code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository_code
        uses: actions/checkout@v2
        
      - name: install_pvs_tools
        run: |
          wget -q -O - https://files.pvs-studio.com/etc/pubkey.txt \
            | sudo apt-key add -
          sudo wget -O /etc/apt/sources.list.d/viva64.list \
            https://files.pvs-studio.com/etc/viva64.list
          sudo apt update
          sudo apt install pvs-studio
          pvs-studio-analyzer credentials ${{ secrets.PVS_STUDIO_FREE_CREDENTIALS }}
          
      - name: build_project
        run: |
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=On -B build .
          cmake --build build -j
          
      - name: analyze_project
        run: |
          pvs-studio-analyzer analyze -f build/compile_commands.json -j
          
      - name: convert_report
        run: |
          plog-converter -t sarif -o pvs-report.sarif PVS-Studio.log
          echo "( print report )"
          cat pvs-report.sarif
          
      - name: publish_report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pvs-report.sarif
          category: PVS-Studio
